vim.keymap.set('n', 'Y', '"xyy"xp', {})
vim.keymap.set('n', 'vv', 'V', {})
vim.keymap.set('n', 'cw', '"_ciw', {})
vim.keymap.set('n', 'ci"', '"_ci"', {})
vim.keymap.set('n', 'ci\'', '"_ci\'', {})

-- vim.keymap.set('n', '\\', ':w<cr>', {})
vim.keymap.set('n', '\\', function() vim.cmd("w") end, {})
vim.keymap.set('n', '|', function() vim.cmd("q") end, {})
-- vim.keymap.set('n', '|', ':q<cr>', {})
