require "extra.my_plugins.float_helper.main".setup()
require "extra.my_plugins.highlights_helper.main".setup()
require "extra.my_plugins.docs_helper.main".setup()
require "extra.my_plugins.lsp_helper.main".setup()
require "extra.my_plugins.treesitter_helper.main".setup()
