return {}
-- 	"mfussenegger/nvim-dap-python",
-- 	config = function ()
-- 		-- require("dap-python").setup("/tmp/py/.virtualenvs/debugpy/bin/python")
-- 		require("dap-python").setup("/Users/dominik/HOME/.local/share/nvim/mason/packages/debugpy/venv/bin/python")
-- -- If using the above, then `/path/to/venv/bin/python -m debugpy --version`
-- -- must work in the shell
-- 	end
-- 	-- config =function ()
-- 		-- require("dap-python").setup({"python"})
-- -- If using the above, then `python -m debugpy --version`
-- -- must work in the shell
-- 	-- end
-- }
